name: make go tag

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  make-go-tag:
    name: make a vM.m.P tag
    outputs:
      status: ${{ job.status }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: make go version tag
        uses: senzing-factory/github-action-make-go-tag@v1

  slack-notification:
    needs: [make-go-tag]
    if: ${{ always() && contains(fromJSON('["failure", "cancelled"]'), needs.make-go-tag.outputs.status ) }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/build-failure-slack-notification.yaml@v2
    with:
      job-status: ${{ needs.make-go-tag.outputs.status }}
